### ISSUE TITLE
build errors: lex required + missing initparser and parser

### ISSUE THREAD

**Issue by DSLituiev** [aaalgo/ljpeg#2]
while running `make` in `jpegdir` I encounter an error that `lex` is not defined in some bash script call. I had to install it using:

`sudo apt-get install flex` and `alias lex='flex'`

Now I am getting next build error:
```
cc  -O3  jpeg.o codec.o huffman.o io.o chendct.o leedct.o lexer.o marker.o stream.o transform.o -lm -o jpeg
jpeg.o: In function `main':
jpeg.c:(.text.startup+0x240f): undefined reference to `initparser'
jpeg.c:(.text.startup+0x2416): undefined reference to `parser'
collect2: error: ld returned 1 exit status
make: *** [jpeg] Error 1
```
indeed, `parser` is referenced in `jpeg.c` but defined only in `prototypes.h`, which is not included. I managed it by lexing manually as in last commented lines in the makefile

**Comment by aaalgo** [comment]
The codebase was polluted by the unsuccessful make when flex was not installed.  Checkout the code from scratch and it should build now.

**Comment by aaalgo** [comment]
Updated README to added flex.  I'm able to reproduce your problem.  But you are probably the last user of this code and already know how to fix it, so I guess a note in README suffices...
