### ISSUE TITLE
syntaxerror after make

### ISSUE THREAD

**Issue by 437432655** [aaalgo/ljpeg#3]
>>> from ljpeg import ljpeg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xuran/ddsm/ljpeg/ljpeg.py", line 12
    print "jpeg is not built yet; use 'cd jpegdir; make' first"
                                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "jpeg is not built yet; use 'cd jpegdir; make' first")?

after make, there is a syntaxerror when I import. When making , there is no error , but just some warnning. Can you do me this favor?

**Comment by aaalgo** [comment]
The code is written in python 2.

**Comment by 437432655** [comment]
oh , yes. 
But when I use python 2 , there is another error .

>>> from ljpeg import ljpeg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name ljpeg

**Comment by aaalgo** [comment]
See this:
```
wdong@w5:~/src/ljpeg$ ls
__init__.py  jpegdir  LICENSE  ljpeg.py  README.md
wdong@w5:~/src/ljpeg$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ljpeg
>>> 
```

**Comment by 437432655** [comment]
Yes , finally I successfully transform the ljpeg.
I really really appreciate that.

**Comment by 437432655** [comment]
oh, I notice you may also research the DDSM dataset.
I want to get the annotations information, the mask、bounding box, do you have any ideas? Thank you very much.

**Comment by aaalgo** [comment]
You are correct.  I think DDSM is the only reason people still use the ljpeg code.  Their dataset contains the annotation.  I do have some code to deal with that, but it's not easy for me to dig that out and for you to use it.

**Comment by 437432655** [comment]
oh，never mind. I have written some code to deal with this annotation. It indeed very rare about ljpeg format. Your code really help me a lot. I'm really sincerely grateful to you.

**Comment by 437432655** [comment]
Hello, I used your code . It's great ! But some image in ddsm seem all black. The pixels of these images are very low. The number of these images is about 100 . Have you noticed this problem? Is there some problem when I used your code ?

**Comment by surabhisnath** [comment]
> Hello, I used your code . It's great ! But some image in ddsm seem all black. The pixels of these images are very low. The number of these images is about 100 . Have you noticed this problem? Is there some problem when I used your code ?

I have faced the exact same problem. Were you able to solve it? I think this is possibly due to the bps value. If the bps value is not 12, seems like the image turns out to be black. Any workaround for this?
